print("Hello Git! I am learning version control.")
print("this is the new line i added")
print("this is the line you get when you pull")
print("added another line")
print("this is the 5th line")
print("this is from anothe branch")
print("another line added from the testing branch")
print("this is from teh lines branch")
print("learning pull requests")
print("this was added from the main branch")
